### ISSUE TITLE
Adruino core version to use

### ISSUE THREAD

**Issue by ryanalden** [starkillerOG/h801-mqtt-json#1]
I had difficulty compiling this with any ESP8266 Arduino Core > 2.2.3.  It might be helpful to specify the core version to use in the documentation.  Otherwise, it's working great -- thanks much!

**Comment by starkillerOG** [comment]
@ryanalden Thanks for pointing this out!
I added the version I used (version 2.5.2) in the readme steps (step 5).
Is it now clear?

Did you find any other parts unclear or had other troubles?

Anything that is not working as you expected with HomeAssistant?

**Comment by ryanalden** [comment]
Hi! Yes, it's clear now.  I also gave another shot at compiling from scratch and had no trouble building with 2.5.2.

At the moment my focus is slight flickering at very-low-level brightness.  ESPhome, Tasmota and this project (with Arduino core 2.2.3, anyway) all exhibit it on my H801.  From what I have read, it's due to underlying Arduino PWM management.  However, at the moment I'm having good results with ESPurna in this regard.  If I run into difficulty with ESPurna, I'll switch back to this project and try compiling with a dev version of Core that has the current waveform PWM fixes.  Thanks again.
