### ISSUE TITLE
OTA page errors out

### ISSUE THREAD

**Issue by steveuk23** [starkillerOG/h801-mqtt-json#3]
Thanks for this it works a treat, hoping to use it alongside Hyperion that I'm setting up.
Although the ota page errors out when I try to access it and i confirmed my module name is correct.
Any ideas.
Thanks

**Comment by starkillerOG** [comment]
@steveuk23 yes, you can use the IP of the module to acces the OTA page: "192.168.1.[IP]/firmware"

**Comment by starkillerOG** [comment]
I will update the documentation to give the IP hint

**Comment by starkillerOG** [comment]
Please let me know if that worked for you

**Comment by steveuk23** [comment]
> Please let me know if that worked for you

Thanks I'll try that tonight when I get home from work.

**Comment by steveuk23** [comment]
> Please let me know if that worked for you
Thanks yep loaded fine with just the IP/firmware
Cheers

**Comment by starkillerOG** [comment]
Closing since the issue has been resolved by using the IP adress
