### ISSUE TITLE
Links with information about hyperion are outdated

### ISSUE THREAD

**Issue by luukberenschot** [starkillerOG/h801-mqtt-json#4]
Hello, thank you for your software, so far everything seems to work great. Only I am unable to connect it to my hyperion instance. The link about the udp stream seems outdated. Could you maybe explain how to setup the udp stream to work with the new Hyperion.NG.

**Comment by starkillerOG** [comment]
I updated the Readme for some additional instruction and I updated the links.
It looks like Hyperion is in the process of updating its documentation, so unfortunately there is not much documentation about the Hyperion UPD raw device, but if you already have hyperion.ng running it schould not be to hard.

If you have any problems, feel free to ask for more information.

**Comment by luukberenschot** [comment]
Thank you, the updated instructions made it more clear and I got everything working now. I only ran into one small issue while setting up. The Udp instance needs to be running while changing its configuration e.g led count. But for the changes to actually have effect the instance needs to be restarted. At least in my case.

**Comment by starkillerOG** [comment]
Good to hear that it is working for you.
If you have any other questions, feel free to open another issue.
