### ISSUE TITLE
How do you find the IP address ?

### ISSUE THREAD

**Issue by steveuk23** [starkillerOG/h801-mqtt-json#5]
Hi i have 2 of these running great now and integrated into Home Assistant.
I've now setup Hyperion which work great and i'm wanting to link hyperion with this device but my problem is the 2 devices don't show on my routers attached devices list so i can't see what IP address they are using.
Do you know how i can find out what ip they are using
Thanks

**Comment by starkillerOG** [comment]
yes, the IP is published in the MQTT topic `LedStrip/LED1/settings/json_status`.
You can use a program like "MQTT Explorer" available in the windows store: https://www.microsoft.com/en-us/p/mqtt-explorer/9pp8sfm082wd?activetab=pivot:overviewtab

**Comment by starkillerOG** [comment]
However to link the H801 to Hyperion, you do not need the IP adress.
Hyperion will publish UDP messages to a multicast adress and port (you need to setup hyperion for UDP raw to a multicast adress with a port number).
The H801 will look for UDP messages in the same multicast adress and port you need to define in the config.h file (of this project) that gets uploaded in the firmware for the H801.
https://github.com/starkillerOG/h801-mqtt-json/blob/93a9af57d7ce9fbece13957033d75b5fe8d0449c/Config.h#L32-L33

**Comment by starkillerOG** [comment]
Also see the settings in the readme: https://github.com/starkillerOG/h801-mqtt-json#udp-streams--hdmi-mode

**Comment by starkillerOG** [comment]
@luukotje just setup Hyperion with this project 3 days ago, so he schould be able to help you.

@luukotje and @steveuk23 maybe one of you can make a PR to add some information to the readme to clearify the steps that you found difficult/unclear.

**Comment by steveuk23** [comment]
> @luukotje just setup Hyperion with this project 3 days ago, so he schould be able to help you.
> 
> @luukotje and @steveuk23 maybe one of you can make a PR to add some information to the readme to clearify the steps that you found difficult/unclear.

Thanks for that i had checked through mqtt explorer as well , obviously not enough lol.
I actually think your instructions are quite clear for the H801 its the hyperion side of it i was struggling with.
I have the H801 running 3 small spot lights with 9 leds in each and thought it would be cool if they synced with the hyperion colours when they are running but i couldn't find any info on how to actually set it up but then worked it out i needed a new instance and controller type and thought i needed the IP address but just couldn't find it.
But should be ok now.
Thanks again

**Comment by luukberenschot** [comment]
That’s great to hear, for finding an IP I often use net analyzer. This is an app on iOS and lists all the devices in the network, this may be easier then doing it through MQTT explorer. I have set up multiple h801 to sync on one hyperion instance recently. If you have any questions, or you can’t completely get it to work I am willing to help you with this. One thing that was bothering me, which is more a problem of hyperion. If you make changes to the instance e.g. add an led in the instance. You have to restart the instance in config for the changes to actually have effect.

**Comment by steveuk23** [comment]
> That’s great to hear, for finding an IP I often use net analyzer. This is an app on iOS and lists all the devices in the network, this may be easier then doing it through MQTT explorer. I have set up multiple h801 to sync on one hyperion instance recently. If you have any questions, or you can’t completely get it to work I am willing to help you with this. One thing that was bothering me, which is more a problem of hyperion. If you make changes to the instance e.g. add an led in the instance. You have to restart the instance in config for the changes to actually have effect.

Thanks for that , not had chance to look at it yet.
But I've realised it might not work anyway as the spot lights I mentioned don't go around the TV like the Hyperion led strips.
One is above it in a cabinet and 2 to the right in cabinets so I can't imagine the colours would  sync with them in strange positions.

**Comment by luukberenschot** [comment]
> > That’s great to hear, for finding an IP I often use net analyzer. This is an app on iOS and lists all the devices in the network, this may be easier then doing it through MQTT explorer. I have set up multiple h801 to sync on one hyperion instance recently. If you have any questions, or you can’t completely get it to work I am willing to help you with this. One thing that was bothering me, which is more a problem of hyperion. If you make changes to the instance e.g. add an led in the instance. You have to restart the instance in config for the changes to actually have effect.
> 
> Thanks for that , not had chance to look at it yet.
> But I've realised it might not work anyway as the spot lights I mentioned don't go around the TV like the Hyperion led strips.
> One is above it in a cabinet and 2 to the right in cabinets so I can't imagine the colours would sync with them in strange positions.

I think that should not be a problem. As you have set up 2 h801 just like me I assume the 2 in the right cabinet are connected to the same controller so they will always both have the same color. I myself also have a setup with 2 h801s both connected to one led strip. One is on the left of my TV the other on the right. What I did is I synced the left side of the TV to one h801 and the other side of the TV to the right one. You can do this by setting an offset in the firmware of one of the h801s, the offset should be 3 in this case. Then you can setup in the Hyperion instance you created 1 led on left and one on right. After restarting all should work.

**Comment by steveuk23** [comment]
> > > That’s great to hear, for finding an IP I often use net analyzer. This is an app on iOS and lists all the devices in the network, this may be easier then doing it through MQTT explorer. I have set up multiple h801 to sync on one hyperion instance recently. If you have any questions, or you can’t completely get it to work I am willing to help you with this. One thing that was bothering me, which is more a problem of hyperion. If you make changes to the instance e.g. add an led in the instance. You have to restart the instance in config for the changes to actually have effect.
> > 
> > 
> > Thanks for that , not had chance to look at it yet.
> > But I've realised it might not work anyway as the spot lights I mentioned don't go around the TV like the Hyperion led strips.
> > One is above it in a cabinet and 2 to the right in cabinets so I can't imagine the colours would sync with them in strange positions.
> 
> I think that should not be a problem. As you have set up 2 h801 just like me I assume the 2 in the right cabinet are connected to the same controller so they will always both have the same color. I myself also have a setup with 2 h801s both connected to one led strip. One is on the left of my TV the other on the right. What I did is I synced the left side of the TV to one h801 and the other side of the TV to the right one. You can do this by setting an offset in the firmware of one of the h801s, the offset should be 3 in this case. Then you can setup in the Hyperion instance you created 1 led on left and one on right. After restarting all should work.

Ah didn't know you could do that I will have a play with that.
But all 3 spots are connected to the same H801 and the Hyperion is on a raspberry Pi controlling one strip of LEDs
Thanks

**Comment by starkillerOG** [comment]
Since I think this is an old issue that has been resolved, I will close it.
If you have any other questions, please feel free to open another issue.
