### ISSUE TITLE
Gamma Correction

### ISSUE THREAD

**Issue by jollybully** [starkillerOG/h801-mqtt-json#6]
how best to incorporate gamma correction to this project?

**Comment by starkillerOG** [comment]
Well if you use it with Hyperion to sync to a TV, you can best setup gamma correction inside Hyperion.

If you want gamma correction even with static colors, some code needs to be added to this project.
There is already a crude way of setting the white balance here:
https://github.com/starkillerOG/h801-mqtt-json/blob/93a9af57d7ce9fbece13957033d75b5fe8d0449c/Config.h#L48

That white balance is applied here in the code:
https://github.com/starkillerOG/h801-mqtt-json/blob/93a9af57d7ce9fbece13957033d75b5fe8d0449c/h801-mqtt-json.ino#L199-L201
That would probably also be the best place to implement gamma corrections.
@jollybully, I would be happy to accept and revieuw a PR to incorporate this if you want.

**Comment by starkillerOG** [comment]
Closing this, since it is a very old issue
